INSERT INTO category (description) values ('American')
INSERT INTO Category (description) values ('Italan')
INSERT INTO Category (description) values ('Mexican')
INSERT INTO Category (description) values ('Greek')
INSERT INTO unit_of_measure (description) VALUES ('Tea spoon')
INSERT INTO unit_of_measure (description) VALUES ('table spoon')
INSERT INTO unit_of_measure (description) VALUES ('cup')
INSERT INTO unit_of_measure (description) VALUES ('Pinch')
INSERT INTO unit_of_measure (description) VALUES ('Ounce')
